DROP TABLE IF EXISTS Taverns;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS BasementRats;
DROP TABLE IF EXISTS Supplies;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Shipments;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS ServiceStatus;
DROP TABLE IF EXISTS TavernServices;
DROP TABLE IF EXISTS Sales;

CREATE TABLE Taverns (Id int IDENTITY PRIMARY KEY, TavernName varchar(250), LocationID int, OwnerID int, Floors tinyint);
CREATE TABLE Users (Id int IDENTITY PRIMARY KEY, Name varchar(250), RoleID int);
CREATE TABLE Location (Id int IDENTITY PRIMARY KEY, Name varchar(100));
CREATE TABLE Roles (Id tinyint IDENTITY PRIMARY KEY, Name varchar(50), Description varchar(MAX));
CREATE TABLE BasementRats (Id int IDENTITY PRIMARY KEY, Name varchar(100));
CREATE TABLE Supplies (Id int IDENTITY PRIMARY KEY, Name varchar(150), Unit varchar(50));
CREATE TABLE Inventory (SupplyId int, TavernId int, LastUpdated date, Amount decimal CONSTRAINT PK_Inventory PRIMARY KEY (SupplyId,TavernId));
CREATE TABLE Shipments (SupplyId int, TavernId int, Cost decimal, Amount decimal, ReceivedDate date, CONSTRAINT PK_Shipment PRIMARY KEY (SupplyId,TavernId,Date));
CREATE TABLE Services (Id int IDENTITY PRIMARY KEY, Name varchar(150));
CREATE TABLE ServiceStatus (Id int IDENTITY PRIMARY KEY, Status varchar(100));
CREATE TABLE TavernServices (TavernId int, ServiceId int, StatusId int, CONSTRAINT PK_Service PRIMARY KEY (TavernId,ServiceId));
CREATE TABLE Sales (TavernId int, ServiceId int, GuestName varchar(250), Price decimal, SaleTime datetime, Amount decimal, CONSTRAINT PK_Sale PRIMARY KEY (TavernId,ServiceId,GuestName,Date));

INSERT INTO Roles (Name, Description) VALUES ('Adventurer', 'Travels far and wide to find new and interesting alcohol and monsters.');
INSERT INTO Roles (Name, Description) VALUES ('Cleaner', 'Keeps their tavern neat and tidy.');
INSERT INTO Roles (Name, Description) VALUES ('Heavy', 'Encourages brawls in the tavern, especially when they are involved.');
INSERT INTO Roles (Name, Description) VALUES ('Bard', 'Always has live entertainment in his tavern, even if they have to be the one to supply it.');
INSERT INTO Roles (Name, Description) VALUES ('Connoisseur', 'Only serves the best food and drink in their establishment.');
INSERT INTO Location (Name) VALUES ('Rillanon');
INSERT INTO Location (Name) VALUES ('Gondor');
INSERT INTO Location (Name) VALUES ('Las Vegas');
INSERT INTO Location (Name) VALUES ('Altea');
INSERT INTO Location (Name) VALUES ('Philadelphia');
INSERT INTO Users (Name, RoleID) VALUES ('Robert Baratheon', 3);
INSERT INTO Users (Name, RoleID) VALUES ('Gordon Ramsey', 5);
INSERT INTO Users (Name, RoleID) VALUES ('Sam Winchester', 1);
INSERT INTO Users (Name, RoleID) VALUES ('Dean Winchester', 3);
INSERT INTO Users (Name, RoleID) VALUES ('Arutha conDoin', 1);
INSERT INTO Taverns (TavernName, LocationID, OwnerID, Floors) VALUES ('Artisenal Ales', 1, 5, 2);
INSERT INTO Taverns (TavernName, LocationID, OwnerID, Floors) VALUES ('Bold Beers', 3, 1, 3);
INSERT INTO Taverns (TavernName, LocationID, OwnerID, Floors) VALUES ('The Winchester' 4, 3, 1);
INSERT INTO Taverns (TavernName, LocationID, OwnerID, Floors) VALUES ('The Better Winchester', 2, 4, 2);
INSERT INTO Taverns (TavernName, LocationID, OwnerID, Floors) VALUES ('Lamb Sauce Lodge', 5, 2, 4);
INSERT INTO BasementRats (Name) VALUES ('Rattigan');
INSERT INTO BasementRats (Name) VALUES ('Cheesy');
INSERT INTO BasementRats (Name) VALUES ('Samuel');
INSERT INTO BasementRats (Name) VALUES ('John');
INSERT INTO BasementRats (Name) VALUES ('Frank');
INSERT INTO Supplies (Name, Unit) VALUES ('Athenian Ale', 'Ounce');
INSERT INTO Supplies (Name, Unit) VALUES ('Brew of Bartholemew', 'Barrel');
INSERT INTO Supplies (Name, Unit) VALUES ('Peanuts', 'Pound');
INSERT INTO Supplies (Name, Unit) VALUES ('Pretzels', 'Bag');
INSERT INTO Supplies (Name, Unit) VALUES ('Sizzling Sweets', 'Piece');
INSERT INTO Inventory (SupplyId, TavernId, LastUpdated, Amount) VALUES (1, 1, 1998-10-05, 1200);
INSERT INTO Inventory (SupplyId, TavernId, LastUpdated, Amount) VALUES (1, 2, 1998-10-05, 1200);
INSERT INTO Inventory (SupplyId, TavernId, LastUpdated, Amount) VALUES (2, 3, 2000-05-07, 20);
INSERT INTO Inventory (SupplyId, TavernId, LastUpdated, Amount) VALUES (5, 5, 2010-06-06, 5000);
INSERT INTO Inventory (SupplyId, TavernId, LastUpdated, Amount) VALUES (4, 4, 2008-02-08, 200);
INSERT INTO Shipments (SupplyId, TavernId, Cost, Amount, ReceivedDate) VALUES (1, 1, 1998-10-05, 500);
INSERT INTO Shipments (SupplyId, TavernId, Cost, Amount, ReceivedDate) VALUES (1, 2, 1998-10-01, 200);
INSERT INTO Shipments (SupplyId, TavernId, Cost, Amount, ReceivedDate) VALUES (2, 3, 1999-05-05, 5);
INSERT INTO Shipments (SupplyId, TavernId, Cost, Amount, ReceivedDate) VALUES (5, 5, 2010-06-01, 1000);
INSERT INTO Shipments (SupplyId, TavernId, Cost, Amount, ReceivedDate) VALUES (4, 4, 2008-01-02, 50);
INSERT INTO Services (Name) VALUES ('Inn Room');
INSERT INTO Services (Name) VALUES ('Darts');
INSERT INTO Services (Name) VALUES ('Armor Repair');
INSERT INTO Services (Name) VALUES ('Target Practice');
INSERT INTO Services (Name) VALUES ('Exorcism');
INSERT INTO ServiceStatus (Status) VALUES ('Active');
INSERT INTO ServiceStatus (Status) VALUES ('Unavailable');
INSERT INTO ServiceStatus (Status) VALUES ('In Progress');
INSERT INTO ServiceStatus (Status) VALUES ('Out of Order');
INSERT INTO ServiceStatus (Status) VALUES ('Unknown');
INSERT INTO TavernServices (TavernId, ServiceId, StatusId) VALUES (3, 5, 3);
INSERT INTO TavernServices (TavernId, ServiceId, StatusId) VALUES (4, 5, 3);
INSERT INTO TavernServices (TavernId, ServiceId, StatusId) VALUES (1, 1, 1);
INSERT INTO TavernServices (TavernId, ServiceId, StatusId) VALUES (2, 3, 1);
INSERT INTO TavernServices (TavernId, ServiceId, StatusId) VALUES (1, 4, 2);
INSERT INTO Sales (TavernId, ServiceId, GuestName, Price, SaleTime, Amount) VALUES (1, 1, 'Frank', 5, 2018-09-08 20:05:12, 1);
INSERT INTO Sales (TavernId, ServiceId, GuestName, Price, SaleTime, Amount) VALUES (3, 5, 'Asmodeus', 100000, 2019-09-11 23:29:05, 1);
INSERT INTO Sales (TavernId, ServiceId, GuestName, Price, SaleTime, Amount) VALUES (4, 5, 'Gabriel', 20000, 2019-09-10 03:03:03, 1);
INSERT INTO Sales (TavernId, ServiceId, GuestName, Price, SaleTime, Amount) VALUES (2, 3, 'Legolas', 1023, 2000-05-19 20:06:53, 2);
INSERT INTO Sales (TavernId, ServiceId, GuestName, Price, SaleTime, Amount) VALUES (1, 1, 'Sasquatch', 20, 1987-03-01 22:11:07, 1);